eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka

server:
  port: 8010

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: Eureka-Server
