eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: localhost

server:
  port: 8040

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://students    # http://localhost:8020
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: lb://schools     # http://localhost:8030
          predicates:
            - Path=/api/v1/schools/**
